from typing import Dict
from hft_backtest.order import Order
from hft_backtest.event_engine import Component, EventEngine

class Account(Component):
    def __init__(self) -> None: ...
    
    # Component 接口
    def start(self, engine: EventEngine) -> None: ...
    def stop(self) -> None: ...

    # 核心事件回调
    def on_order(self, order: Order) -> None: ...
    
    # 查询接口
    def get_positions(self) -> Dict[str, float]: ...
    def get_orders(self) -> Dict[int, Order]: ...
    def get_prices(self) -> Dict[str, float]: ...
    def get_balance(self) -> float: ...
    def get_equity(self) -> float: ...
    
    # 统计接口
    def get_total_turnover(self) -> float: ...
    def get_total_commission(self) -> float: ...
    def get_total_funding_fee(self) -> float: ...
    def get_total_trade_pnl(self) -> float: ...
    def get_total_trade_count(self) -> int: ...