from typing import Dict
from hft_backtest.order import Order

class Account:
    def __init__(self) -> None: ...
    
    # 核心事件回调
    def on_order(self, order: Order) -> None: ...
    
    # 查询接口
    def get_positions(self) -> Dict[str, float]: ...
    def get_orders(self) -> Dict[int, Order]: ...
    def get_prices(self) -> Dict[str, float]: ...
    def get_balance(self) -> float: ...
    def get_equity(self) -> float: ...