from _typeshed import Incomplete
from typing import ClassVar

__test__: dict

class Event:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    producer: Incomplete
    source: Incomplete
    timestamp: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def derive(self, *args, **kwargs): ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...
