from hft_backtest.event_engine import Component, EventEngine
from hft_backtest.order import Order

class MatchEngine(Component):
    def on_order(self, order: Order) -> None: ...
    def start(self, engine: EventEngine) -> None: ...
    def stop(self) -> None: ...