from typing import Dict, Any, Optional
from hft_backtest.account import Account
from hft_backtest.event_engine import EventEngine
from hft_backtest.order import Order
from hft_backtest.okx.event import OKXTrades, OKXFundingRate, OKXDelivery

class OKXAccount(Account):
    # --- 核心状态 (对应 .pxd 中的 cdef public 字段) ---
    cash_balance: float
    position_dict: Any  # 实际上是 defaultdict(int)
    order_dict: Dict[int, Order]
    price_dict: Dict[str, float]

    # --- 累计统计 ---
    total_turnover: Any
    total_commission: Any
    total_funding_fee: Any
    net_cash_flow: Any
    total_trade_count: Any

    def __init__(self, initial_balance: float = 0.0) -> None: ...
    
    def start(self, engine: EventEngine) -> None: ...
    def stop(self) -> None: ...

    # --- 事件处理 ---
    def on_order(self, order: Order) -> None: ...
    def on_trade_data(self, event: OKXTrades) -> None: ...
    def on_funding_data(self, event: OKXFundingRate) -> None: ...
    def on_delivery_data(self, event: OKXDelivery) -> None: ...

    # --- 查询与计算接口 ---
    def get_positions(self) -> Dict[str, float]: ...
    def get_orders(self) -> Dict[int, Order]: ...
    def get_prices(self) -> Dict[str, float]: ...
    def get_balance(self) -> float: ...
    
    def get_position_cashvalue(self) -> float: ...
    def get_equity(self) -> float: ...
    def get_total_margin(self) -> float: ...
    def get_leverage(self) -> Optional[float]: ...

    # --- 统计数据 Getter ---
    def get_total_turnover(self) -> float: ...
    def get_total_trade_count(self) -> int: ...
    def get_total_commission(self) -> float: ...
    def get_total_funding_fee(self) -> float: ...
    def get_total_trade_pnl(self) -> float: ...