from hft_backtest.matcher import MatchEngine
from hft_backtest.event_engine import EventEngine
from hft_backtest.order import Order
from hft_backtest.okx.event import OKXBookticker, OKXTrades, OKXDelivery

class OKXMatcher(MatchEngine):
    symbol: str
    taker_fee: float
    maker_fee: float
    
    def __init__(self, symbol: str, taker_fee: float = ..., maker_fee: float = ...) -> None: ...
    def start(self, engine: EventEngine) -> None: ...
    def on_order(self, order: Order) -> None: ...
    def on_bookticker(self, event: OKXBookticker) -> None: ...
    def on_trade(self, event: OKXTrades) -> None: ...
    def on_delivery(self, event: OKXDelivery) -> None: ...